insults = ["I know you find yourself to be magnificent and handsome like the great eagle, but I must admit that your presence reminds me more of the dead fish caught inside of said eagle’s mouth.", "You know, even though armadillos have a bad tendency to turn up dead on the side of highways, they’re still kind of cute the rest of the time.   You rather remind me of an armadillo, minus the latter half of the statement.", " You swine. You vulgar little maggot. You worthless bag of filth. As we say in Texas, you couldnt pour water out of a boot with instructions printed on the heel. You are a canker, an open wound. I would rather kiss a lawyer than be seen with you. You took your last vacation inthe Isles of Langerhan.", " You're a putrescent mass, a walking vomit. You are a spineless little worm deserving nothing but the profoundest contempt. You are a jerk, a cad, a weasel. Your life is a monument to stupidity. You are a stench, a revulsion, a big suck on a sour lemon.", " You are a bleating foal, a curdled staggering mutant dwarf smeared richly with the effluvia and offal accompanying your alleged birth into a hostile world. You are an insensate, blinking calf, meaningful to nobody, abandoned by the puke-drooling, giggling beasts who sired you and then died of shame in recognition of what they had done. They were a bit late.",
    " I will never get over the embarrassment of belonging to the same species as you. You are a monster, an ogre, a malformity. I barf at the very thought of you. You have all the appeal of a paper cut. Lepers avoid you. You are vile, worthless, less than nothing. You are a weed, a fungus, the dregs of this earth. And did I mention that you smell?",
    " Try to edit your responses of unnecessary material before attempting to impress us with your insight. The evidence that you are a nincompoop will still be available to readers, but they will be able to access it ever so much more rapidly.",
    " You snail-skulled little rabbit. Would that a hawk pick you up, drive its beak into your brain, and upon finding it rancid set you loose to fly briefly before spattering the ocean rocks with the frothy pink shame of your ignoble blood. May you choke on the queasy, convulsing nausea of your own trite, foolish beliefs.",
    " You are weary, stale, flat and unprofitable. You are grimy, squalid, nasty and profane. You are foul and disgusting. You're a fool, an ignoramus. Monkeys look down on you. Even sheep won't have sex with you. You are unreservedly pathetic, starved for attention, and lost in a land that reality forgot. You are not ANSI compliant. You have a couple of address lines shorted together. You should be promoted to Engineering Manager.",
    " And what meaning do you expect your delusionally self-important statements of unknowing, inexperienced opinion to have with us? What fantasy do you hold that you would believe that your tiny-fisted tantrums would have more weight than that of a leprous desert rat, spinning rabidly in a circle, waiting for the bite of the snake?",
    " You are a waste of flesh. You have no rhythm. You are ridiculous and obnoxious. You are the moral equivalent of a leech. You are a living emptiness, a meaningless void. You are sour and senile. You are a loathsome disease, a puerile slack-jawed drooling meatslapper. You make Quakers shout and strike Pentecostals silent. Your mother had to tie a pork chop around your neck just to get your dog to play  with you.  You think P.D.Q. Bach is the greatest composer who ever lived.  You prefer L. Ron Hubbard to Larry Niven and Jerry Pournelle.  Hee-Haw is too deep for you.  You would watch test patterns all day if the other inmates would let you.",
    " On a good day you're a half-wit. You remind me of drool. You are deficient in all that lends character. You have the personality of wallpaper. You are dank and filthy. You are asinine and benighted. You are the source of all unpleasantness. You spread misery and sorrow wherever you go.",
    " Fuck you, you unclever whiny piece of shit. You fucking ass-cum guzzler. Go dig through your mom's crabs infested-vagina and find a crusty old tampon with bloody pubic hairs on it, and rub your slimy 1 inch cock and cum in her bloody, puss filled vagina.",
    " I cannot believe how incredibly stupid you are. I mean rock-hard stupid. Dehydrated-rock-hard stupid. Stupid so stupid that it goes way beyond the stupid we know into a whole different dimension of stupid. You are trans-stupid stupid. Meta-stupid. Stupid collapsed on itself so far that even the neutrons have collapsed.  Stupid gotten so dense that no intellect can escape. Singularity stupid. Blazing hot mid-day sun on Mercury stupid. You emit more stupid in one second than our entire galaxy emits in a year. Quasar stupid. Your writing has to be a troll. Nothing in our universe can really be this stupid. Perhaps this is some primordial fragment from the original big bang of stupid. Some pure essence of a stupid so uncontaminated by anything else as to be beyond the laws of physics that we know. I'm sorry. I can't go on. This is an epiphany of stupid for me. After this, you may not hear from me again for a while. I don't have enough strength left to deride your ignorant questions and half baked comments about unimportant trivia, or any of the rest of this drivel. Duh.",
    " The only thing worse than your logic is your manners. I have snipped away most of what you wrote, because, well... it didn't really say anything. Your attempt at constructing a creative flame was pitiful. I mean, really, stringing together a bunch of insults among a load of babbling was hardly effective... Maybe later in life, after you have learned to read, write, spell, and count, you will have more success. True, these are rudimentary skills that many of us normal people take for granted that everyone has an easy time of mastering. But we sometimes forget that there are challenged persons in this world who find these things more difficult. If I had known, that this was your case then I would have never read your post. It just wouldn't have been right. Sort of like parking in a handicap space. I wish you the best of luck in the emotional, and social struggles that seem to be placing such a demand on you.",
    " You are hypocritical, greedy, violent, malevolent, vengeful, cowardly, deadly, mendacious, meretricious, loathsome, despicable, belligerent, opportunistic, barratrous, contemptible, criminal, fascistic, bigoted, racist, sexist, avaricious, tasteless, idiotic, brain-damaged, imbecilic, insane, arrogant, deceitful, demented, lame, self-righteous, Byzantine, conspiratorial, satanic, fraudulent, libelous, bilious, splenetic, spastic, ignorant, clueless, illegitimate, harmful, destructive, dumb, evasive, double-talking, devious, revisionist, narrow, manipulative, paternalistic, fundamentalist, dogmatic, idolatrous, unethical, cultic, diseased, suppressive, controlling, restrictive, malignant, deceptive, dim, crazy, weird, dystopic, stifling, uncaring, plantigrade, grim, unsympathetic, jargon-spouting, censorious, secretive, aggressive, mind-numbing, abrasive, poisonous, flagrant, self-destructive, abusive, socially-retarded, puerile, clueless, and generally Not Good.",
    " On an intelligence scale of 1 to 10 (10 corresponding to the highest attainable IQ) you're rating is so far into negative numbers that one would need to travel into another quantum reality in order to even catch who keeps slamming into the picture window trying to get that other bird it keeps seeing", "You are so clueless that if you dressed in a clue skin, doused yourself in clue musk, and did the clue dance in the middle of a field of horny clues at the height of clue mating season, you still would not have a clue. If you were a movie you would be a double feature; _Battlefield_Earth_ and _Moron_Movies_II_. You would be out of focus.",
    " To call you a parasite would be injurious to the thousands of honest parasitic species. You are worse than vermin, for vermin does not pretend to be what it is not. You are truly human garbage. ", "You are a fiend and a sniveling coward, and you have bad breath. You are the unholy spawn of a bandy-legged hobo and a syphilitic camel. You wear strangely mismatched clothing with oddly placed stains. You are degenerate, noxious and depraved. I feel debased just knowing that you exist. I despise everything about you, and I wish you would go away. You are jetsam who dreams of becoming flotsam. You won't make it. I beg for sweet death to come and remove me from a world which became unbearable when the bioterrorists designed you.",
    " You smarmy lagerlout git. You bloody woofter sod. Bugger off, pillock. You grotty wanking oik artless base-court apple-john. You clouted boggish foot-licking half-twit. You dankish clack-dish plonker. You gormless crook-pated tosser. You bloody churlish boil-brained clotpole ponce. You craven dewberry pisshead cockup pratting naff. You cockered bum-bailey poofter. You gob-kissing gleeking flap-mouthed coxcomb. You dread-bolted fobbing beef-witted clapper-clawed flirt-gill. You jetere steatopygous pilgarlick hircine whigmaleerious rhadamanthine lintlicker. I refer you to the reply given in the case of Arkell v. Pressdram.", " you are a flatulent, whelk obsessed bottom gurgler with the style and grace of a leprous baboon. if I had only known that you were possessed of such a singular body aroma, I should have attempted to conduct our meeting through the medium of signal fires, you barely sane, badger-throwing,egg-headed malodourus midget of questionable parentage.",
    "  You remind me of a yellowjacket wasp:  Not only do you freak the hell out of me, but I also can’t tell if there’s actually a reason for your existence. ", "You're so unattractive that you are the foremost contributor to the heat death of the universe, and that much is amplified by the exemplary lack of intelligence that actually gives you the arrogance to attempt to use such a barbaric and essentially pointless line to attempt to \"roast\" me, as those of the intelligence level tantamount to that of an ape- Oh, excuse me, I meant to that of your own. Oh, and one more thing. Once you have deciphered the meaning of this and translated it from English to your own little dialect of Gibberish. I would say \"good day\" but my wishes would be wasted on the scum of society such as yourself."
];
module.exports = {
    insults: insults
}
